Add some changed from dmagellan build script into chtc build script

diff --git a/build-worker-tarball b/build-worker-tarball
--- a/build-worker-tarball
+++ b/build-worker-tarball
@@ -11,8 +11,18 @@ realpath () {
 }
 
 
+if [[ -n $_CONDOR_SCRATCH_DIR ]]; then
+    HOME=$_CONDOR_SCRATCH_DIR
+    TMPDIR=${TMPDIR:-$_CONDOR_SCRATCH_DIR/tmp}
+    mkdir -p "$TMPDIR"
+    export HOME TMPDIR
+fi
+
 work_dir=$(mktemp -dt dask_condor_worker.XXXXXX)
-trap 'rm -rf "$work_dir"' EXIT
+# if not running under condor, clean up the work dir ourselves; otherwise,
+# condor will do that for us on job removal, and for interactive jobs, we'd
+# like to keep it for debugging
+[[ -n $_CONDOR_SCRATCH_DIR ]] || trap 'rm -rf "$work_dir"' EXIT
 
 if [[ $# -lt 2 ]]; then
     echo "Usage: $(basename $0) <source_archive> <target_archive> [<extra_requirements_file>]"
